### PR TITLE
Auth service

### PR DESCRIPTION
**Pull request by kasp441**
a working Auth Service with primary functions done

### CODE REVIEW

**Review by JensIssa — CHANGES_REQUESTED** [review]
Please do Pascal case in all methods.

**Comment by kasp441** [comment]
pascal changes have been adressed

**Review by JensIssa — CHANGES_REQUESTED** [review]
Please rename the objects TokenBE and LoginBE, to Token and Login.

**Comment by kasp441** [comment]
names of Be have been refactored

**Review by JensIssa — APPROVED** [review]
LGTM!

**Pull request merged**
